
export const GET_ALL_SNEAKERS = "GET_ALL_SNEAKERS";
export const GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST';
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
export const GET_SEARCH_NOTFOUND = 'GET_SEARCH_NOTFOUND';
export const GET_ALL_FILTER = ' GET_ALL_FILTER';
export const RESET_CURRENTPAGE = "RESET_CURRENTPAGE"
export const BRAND_VALUE = "BRAND_VALUE"
export const COLOR_VALUE = "COLOR_VALUE"
export const ORDER_PRICE = " ORDER_PRICE"
export const SIZE_VALUE = "SIZE_VALUE"