
export const GET_ALL_SNEAKERS = "GET_ALL_SNEAKERS";
export const GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST';
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
export const GET_SEARCH_NOTFOUND = 'GET_SEARCH_NOTFOUND';
export const GET_ALL_FILTER = ' GET_ALL_FILTER';